#!/bin/bash
"exec" "snakemake" "--printshellcmds" "--snakefile" "$0" "--jobs" "5"

import glob
import os.path
import itertools

SOURCE_DIR = '../../_m'
EXT = '.bam'


def sample_dict_iter(path, ext):
    for filename in glob.iglob(path+'/*'+ext):
        sample = os.path.basename(filename)[:-len(ext)]
        yield sample, {'filename': SOURCE_DIR + '/' + sample + '.bam'}

        
SAMPLE_DICT = {k:v for k,v in sample_dict_iter(SOURCE_DIR, EXT)}

rule all:
    input:
        expand('../_m/{sample}.{ext}',
               sample=SAMPLE_DICT.keys(),
	       ext=['bgz', 'bgz.tbi'])


rule tabix:
    input:
        '../../_m/{sample}.bam'

    output:
        bgz = '../_m/{sample}.bgz',
        tbi = '../_m/{sample}.bgz.tbi'

    params:
        sample = '{sample}'

    shell:
        '''

    TMP_DIR='tmp.{params.sample}'
    mkdir ${{TMP_DIR}}

    export LC_ALL=C

    ( samtools view {input} | ../_h/sam_to_tabix.py  | sort --temporary-directory=${{TMP_DIR}} --buffer-size=10G -k1,1 -k2,2n -k3,3n | bgzip -c > {output.bgz} ) 2> {params.sample}.stderr
    
    rmdir ${{TMP_DIR}}
    
    tabix -s 1 -b 2 -e 3 -0 {output.bgz}

'''
